### ISSUE TITLE
UBSAN: array-index-out-of-bounds with kernel 6.5

### ISSUE THREAD

**Issue by brierjon** [pop-os/virtualbox#12]
Flagging this for tracking and testing.

The same issue as reported by another in https://www.virtualbox.org/ticket/21877 on a Thelio Mira R3 with Pop!_OS 22.04 kernel 6.5.6-76060506-generic and the current Pop Shop supplied Virtualbox 7.0.10_Ubuntu r158379 from this repo is installed. A later version, 7.0.12 was released the 17th October 2023 is reported not to have fixed this - https://forums.virtualbox.org/viewtopic.php?t=110315. 

The 7.0.12 update also added support for kernels 6.5 & 6.6 for the Linux guest additions (https://www.virtualbox.org/wiki/Changelog-7.0#v12).

Limited report from Dmesg:
[   25.629076] UBSAN: array-index-out-of-bounds in /var/lib/dkms/virtualbox/7.0.10/build/vboxdrv/SUPDrvGip.c:4274:52
[   25.629077] index 2 is out of range for type 'SUPGIPCPU [1]'
[   25.629078] CPU: 16 PID: 2296 Comm: iprt-VBoxTscThr Tainted: G           OE      6.5.6-76060506-generic #202310061235~1697396945~22.04~9283e32
[   25.629079] Hardware name: System76 Thelio Mira/Thelio Mira, BIOS F8d Z5 05/10/2023
[   25.629080] Call Trace:
[   25.629080]  <TASK>
[   25.629081]  dump_stack_lvl+0x48/0x70
[   25.629083]  dump_stack+0x10/0x20
[   25.629084]  __ubsan_handle_out_of_bounds+0xc6/0x110
[   25.629086]  supdrvTscDeltaThread+0x72d/0x7c0 [vboxdrv]
[   25.629096]  ? srso_alias_return_thunk+0x5/0x7f
[   25.629099]  ? __pfx_rtThreadNativeMain+0x10/0x10 [vboxdrv]
[   25.629109]  rtThreadMain+0x34/0x80 [vboxdrv]
[   25.629120]  rtThreadNativeMain+0x1b/0x30 [vboxdrv]
[   25.629131]  kthread+0xef/0x120
[   25.629133]  ? __pfx_kthread+0x10/0x10
[   25.629134]  ret_from_fork+0x44/0x70
[   25.629136]  ? __pfx_kthread+0x10/0x10
[   25.629138]  ret_from_fork_asm+0x1b/0x30
[   25.629141]  </TASK>
[   25.629142] ================================================================================
[   25.629143] ================================================================================

**Comment by leviport** [comment]
I believe this is a duplicate of https://github.com/pop-os/linux/issues/285 and not specifically related to Virtualbox

**Comment by brierjon** [comment]
Virtualbox release 7.0.18 states it addressed the UBSAN issues per the [changelog](https://www.virtualbox.org/wiki/Changelog-7.0#v18) closing Virtualbox ticket [21877](https://www.virtualbox.org/ticket/21877). 

Also note 7.0.16 "Linux Guest Additions: Added initial support for kernel 6.8 "

**Comment by brierjon** [comment]
7.0.18 deployed - not seeing UBSAN at this point. closing.
